plugin:
    name: 'albrightlabs.sitemaprobotshumans::lang.plugin.name'
    description: 'albrightlabs.sitemaprobotshumans::lang.plugin.description'
    author: 'Albright Labs LLC'
    icon: oc-icon-sitemap
    homepage: 'https://albrightlabs.com'

permissions:
    albrightlabs.sitemaprobotshumans.access_settings:
        tab: 'Sitemap, Robots, Humans'
        label: 'Manage sitemap, robots, and humans settings'